name: designhub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2  
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  provider: ^6.1.4
  cloud_firestore: ^5.6.6
  google_fonts: 
  photo_view: ^0.14.0 
  app_settings: ^5.2.0
  firebase_storage: ^12.4.5
  link_text: ^0.2.1
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  min_sdk_android: 21
  
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true