// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBms5xGLR0uhgP_XDDzXhOu1yWcL0EzXnk',
    appId: '1:932954488084:web:019dcaf1789de0b9885601',
    messagingSenderId: '932954488084',
    projectId: 'designhub-9d077',
    authDomain: 'designhub-9d077.firebaseapp.com',
    storageBucket: 'designhub-9d077.firebasestorage.app',
    measurementId: 'G-1LHTR2870S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeaZ3cCwDtzHYP6V01JmO8Pgx94LUx5i0',
    appId: '1:932954488084:android:b32400e064cbe4b8885601',
    messagingSenderId: '932954488084',
    projectId: 'designhub-9d077',
    storageBucket: 'designhub-9d077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP2D99WRchSdVAXjXcLOoUqJQGfOk1Eas',
    appId: '1:932954488084:ios:dc9b75c4fda6fb76885601',
    messagingSenderId: '932954488084',
    projectId: 'designhub-9d077',
    storageBucket: 'designhub-9d077.firebasestorage.app',
    iosBundleId: 'com.example.designhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP2D99WRchSdVAXjXcLOoUqJQGfOk1Eas',
    appId: '1:932954488084:ios:dc9b75c4fda6fb76885601',
    messagingSenderId: '932954488084',
    projectId: 'designhub-9d077',
    storageBucket: 'designhub-9d077.firebasestorage.app',
    iosBundleId: 'com.example.designhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBms5xGLR0uhgP_XDDzXhOu1yWcL0EzXnk',
    appId: '1:932954488084:web:8e43daf81f508ca0885601',
    messagingSenderId: '932954488084',
    projectId: 'designhub-9d077',
    authDomain: 'designhub-9d077.firebaseapp.com',
    storageBucket: 'designhub-9d077.firebasestorage.app',
    measurementId: 'G-32XNZPJMJ0',
  );
}
